apiVersion: v1
kind: Secret
metadata:
  name: ${{ values.name }}-${{ values.sqsName }}-awscreds
  labels:
    bridges.triggermesh.io/id: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
stringData:
  aws_access_key_id: ${{ values.sqsAccessKeyId }}
  aws_secret_access_key: ${{ values.sqsSecretAccessKey }}
