apiVersion: sources.triggermesh.io/v1alpha1
kind: AWSSQSSource
metadata:
  name: ${{ values.name }}-${{ values.sqsName }}
  labels:
    bridges.triggermesh.io/id: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  arn: ${{ values.sqsArn }}
  receiveOptions:
    visibilityTimeout: 30m
  auth:
    credentials:
      accessKeyID:
        valueFromSecret:
          name: ${{ values.name }}-${{ values.sqsName }}-awscreds
          key: aws_access_key_id
      secretAccessKey:
        valueFromSecret:
          name: ${{ values.name }}-${{ values.sqsName }}-awscreds
          key: aws_secret_access_key
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: ${{ values.name }}-broker
