apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: ${{ values.name }}-function-trigger
  labels:
    bridges.triggermesh.io/id: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  broker: ${{ values.name }}-broker
  filter:
    attributes:
      type: com.amazon.sqs.message
  subscriber:
    ref:
      apiVersion: flow.triggermesh.io/v1alpha1
      kind: Transformation
      name: ${{ values.name }}-transformation
